# Generated by Django 3.2.25 on 2024-07-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=40)),
                ('project_class', models.CharField(choices=[('ITD', 'IT documents'), ('SD', 'Staff documents'), ('ED', 'Exam documents'), ('STD', 'Student documents'), ('EXD', 'External documents'), ('MD', 'Marketing documents')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
