# Generated by Django 3.2.25 on 2024-07-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0002_project_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
