# Generated by Django 3.2.25 on 2024-07-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0005_alter_file_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_bytes',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
