# Generated by Django 3.2.25 on 2024-07-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0006_alter_file_file_bytes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_bytes',
            field=models.BinaryField(),
        ),
    ]
